version: '3.8'
services:
  impala:
    image: apache/impala:4.4.1-impala_quickstart_hms
    container_name: impala-quickstart
    ports:
      - "21000:21000"   # Impala Shell port
      - "21050:21050"   # JDBC/ODBC port
      - "25000:25000"   # Web UI
    environment:
      - IMPALA_ROLE=quickstart
    volumes:
      - ./data:/opt/impala/data
    stdin_open: true
    tty: true